### PR TITLE
#27 - vs-code: Build tag json files into a single html extension json file

### PR DESCRIPTION
**Pull request by adam-werner**
Single html-data.json file for tags
- generated html-data.json file from https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directives
- updated package.json to point to single json file

@KevinJump -- I've built something locally that is running through the list of directives off of Our, parsed through the content and then build out the single umbraco.html-data.json file.

Please let me know what you think -- thank you!

### CODE REVIEW

**Comment by KevinJump** [comment]
WOOT! - I will take a look.

do you think its something that could run as a build step ? - a yaml file thing would be super low maintenance.

**Comment by KevinJump** [comment]
this sir is an awesome PR.

**Comment by adam-werner** [comment]
> WOOT! - I will take a look.
> 
> do you think its something that could run as a build step ? - a yaml file thing would be super low maintenance.

I think it could be.  Would you be able to describe your vision here?  Are we talking about a build step within this project or looking to the Umbraco build mentioned in one of the other issues.  I'm game for considering and trying out anything in setting this up, please just let me know!  Thank you!

**Comment by KevinJump** [comment]
HI, I will add a new issue - but I would say a build step in this project would be a start. 

if it works then maybe a PR could be added to the core Umbraco project to create the json along with the docs (then we could pull it) - but as a first step something that builds the file here would be ace 

*but* the reality is this part of the docs doesn't change that much - so its more of a "nice to have interesting exercise in build scripts" then a thing needed now we have the one of generation file.

**Comment by adam-werner** [comment]
That sounds good.  I should have let you know though that I have written
the bit to scrape and build the JSON in C#.  Would that prove to be
problematic as part of a build script?  Sorry, I'm newer to build scripts
and I'm not certain how that would fit but I'm open to all ideas.

**Pull request merged**
