### PR TITLE
Put tag-name in a local string constant?

### PR DESCRIPTION
**Pull request by leekelleher**
Hi @KevinJump, what are your thoughts on this?

I was thinking that if the tag-name is defined in multiple places, we could have a string constant for re-use?

I've marked this PR as a draft, if you're happy with the idea, I'll add in the rest and update the PR.

### CODE REVIEW

**Comment by KevinJump** [comment]
yeah, will make it a lot easier to manage and spot mistakes. 👍

**Comment by leekelleher** [comment]
@KevinJump I've done the main ones that we have in the project (so far). 

The `umb-pane` and `umb-panel` didn't have a corresponding class, so I'll add them in due course.

**Comment by leekelleher** [comment]
Putting the PR back in draft. I'll do the other ones now.

**Comment by leekelleher** [comment]
OK, all good now.

I've made some other additions/tweaks, but they'll be better as separate PRs.

**Comment by KevinJump** [comment]
Cool, i will wait off on building a new release & I noticed a missing tag the other day . i need to remember what it was.

**Comment by leekelleher** [comment]
Super quick merge, thanks Kev! 🌟 

I wanted to add in the `umb-code-snippet` directive, I find myself using it a lot for debugging at the moment (great for copying JSON blobs).

**Comment by leekelleher** [comment]
@KevinJump FYI, I'm done with PRs for today. 😄

**Pull request merged**
